// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestApi3K.DataBaseContext;

#nullable disable

namespace TestApi3K.Migrations
{
    [DbContext(typeof(ContextDb))]
    [Migration("20251112161559_third")]
    partial class third
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TestApi3K.Model.Users", b =>
                {
                    b.Property<int>("id_User")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_User"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("level1score")
                        .HasColumnType("int");

                    b.Property<int>("level2score")
                        .HasColumnType("int");

                    b.Property<int>("level3score")
                        .HasColumnType("int");

                    b.HasKey("id_User");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TestApi3K.Model.UsersRecord", b =>
                {
                    b.Property<int>("id_Record")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_Record"));

                    b.Property<int>("id_Achievement")
                        .HasColumnType("int");

                    b.Property<int>("id_User")
                        .HasColumnType("int");

                    b.HasKey("id_Record");

                    b.HasIndex("id_User");

                    b.ToTable("UsersRecord");
                });

            modelBuilder.Entity("TestApi3K.Model.UsersRecord", b =>
                {
                    b.HasOne("TestApi3K.Model.Users", "User")
                        .WithMany("UserAchievements")
                        .HasForeignKey("id_User")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TestApi3K.Model.Users", b =>
                {
                    b.Navigation("UserAchievements");
                });
#pragma warning restore 612, 618
        }
    }
}
